#include <iostream>
#include <string>
using namespace std;

struct MenuItem {
    string Item;
    string Type;
    double Price;
};

class CoffeeShop {
private:
    string Name;
    MenuItem* Menu;
    int MenuSize;
    string* Orders;
    int OrdersSize;

public:
    // Parameterized Constructor
    CoffeeShop(const string& ShopName, const MenuItem* menuItems, int menuSize) 
        : Name(ShopName), MenuSize(menuSize), Orders(nullptr), OrdersSize(0) {
        Menu = new MenuItem[MenuSize];
        for (int i = 0; i < MenuSize; ++i) {
            Menu[i] = menuItems[i];
        }
    }

    // Destructor
    ~CoffeeShop() {
        delete[] Menu;
        delete[] Orders;
    }

    // AddOrder Method
    string AddOrder(const string& ItemName) {
        bool exists = false;
        for (int i = 0; i < MenuSize; ++i) {
            if (Menu[i].Item == ItemName) {
                exists = true;
                break;
            }
        }
        if (!exists) {
            return "Sorry, we don't have '" + ItemName + "' on the menu right now.";
        }
        
        // Resize Orders array
        string* NewOrders = new string[OrdersSize + 1];
        for (int i = 0; i < OrdersSize; ++i) {
            NewOrders[i] = Orders[i];
        }
        NewOrders[OrdersSize] = ItemName;
        
        delete[] Orders;
        Orders = NewOrders;
        OrdersSize++;
        return "Your order for '" + ItemName + "' has been placed.";
    }

    // FulfillOrder Method
    string FulfillOrder() {
        if (OrdersSize == 0) {
            return "All pending orders have been fulfilled.";
        }
        string ReadyItem = Orders[0];
        
        // Remove fulfilled order
        if (OrdersSize == 1) { // Only one item in the order list
            delete[] Orders;
            Orders = nullptr;
            OrdersSize = 0;
        } else { // Multiple items in the order list
            string* NewOrders = new string[OrdersSize - 1];
            for (int i = 1; i < OrdersSize; ++i) {
                NewOrders[i-1] = Orders[i];
            }
            delete[] Orders;
            Orders = NewOrders;
            OrdersSize--;
        }
        return "Your '" + ReadyItem + "' is ready!";
    }

    // ListOrders Method
    string* ListOrders(int& Size) const {
        Size = OrdersSize;
        if (Size == 0){
            return nullptr;
        }
        string* OrderList = new string[Size];
        for (int i = 0; i < Size; ++i) {
            OrderList[i] = Orders[i];
        }
        return OrderList;
    }

    // DueAmount Method
    double DueAmount() const {
        double Total = 0.0;
        for (int i = 0; i < OrdersSize; ++i) {
            for (int j = 0; j < MenuSize; ++j) {
                if (Orders[i] == Menu[j].Item) {
                    Total += Menu[j].Price;
                    break;
                }
            }
        }
        return Total;
    }

    // CheapestItem Method
    string CheapestItem() const {
        if (MenuSize == 0){
            return "";
        }
        string Cheapest = Menu[0].Item;
        double MinPrice = Menu[0].Price;
        
        for (int i = 1; i < MenuSize; ++i) {
            if (Menu[i].Price < MinPrice) {
                MinPrice = Menu[i].Price;
                Cheapest = Menu[i].Item;
            }
        }
        return Cheapest;
    }

    // DrinksOnly Method
    string* DrinksOnly(int& Count) const {
        Count = 0;
        for (int i = 0; i < MenuSize; ++i) {
            if (Menu[i].Type == "drink"){
                Count++;
            }
        }
        if (Count == 0){
            return nullptr;
        }    
        
        string* Drinks = new string[Count];
        int Index = 0;
        for (int i = 0; i < MenuSize; ++i) {
            if (Menu[i].Type == "drink") {
                Drinks[Index++] = Menu[i].Item;
            }
        }
        return Drinks;
    }

    // FoodOnly Method
    string* FoodOnly(int& Count) const {
        Count = 0;
        for (int i = 0; i < MenuSize; ++i) {
            if (Menu[i].Type == "food"){
                Count++;
            }
        }
        if (Count == 0) {
            return nullptr;
        }
        string* Foods = new string[Count];
        int Index = 0;
        for (int i = 0; i < MenuSize; ++i) {
            if (Menu[i].Type == "food") {
                Foods[Index++] = Menu[i].Item;
            }
        }
        return Foods;
    }
};

int main() {
    // sample input generated by Ai

    MenuItem Items[] = {
        {"Iced Coffee", "drink", 8.0},
        {"Cappuccino", "drink", 5.0},
        {"Latte", "drink", 4.5},
        {"Sandwich", "food", 8.0},
        {"Croissant", "food", 3.5},
        {"Pastries", "food", 5.5},
    };

    CoffeeShop Shop("Novel & Nibble", Items, 6);
    cout << "Welcome to Novel & Nibble! Enjoy a delightful coffee break with a good book." << endl;
    cout << "-------------------------" << endl;
    
    int DrinkCount;
    string* Drinks = Shop.DrinksOnly(DrinkCount);
    cout << "Drinks Available (" << DrinkCount << "):" << endl;
    for (int i = 0; i < DrinkCount; ++i) {
        cout << " - " << Drinks[i] << endl;
    }
    delete[] Drinks;
    
    int FoodCount;
    string* Foods = Shop.FoodOnly(FoodCount);
    cout << "\nFood Options (" << FoodCount << "):" << endl;
    for (int i = 0; i < FoodCount; ++i) {
        cout << " - " << Foods[i] << endl;
    }
    delete[] Foods;
    
    cout << "\nCheapest item on the menu: " << Shop.CheapestItem() << endl;
    return 0;
}
